create table account (
    id bigint generated by default as identity,
    role_id bigint not null,
    firstname varchar(50) not null,
    lastname varchar(50) not null,
    username varchar(64) not null unique,
    password varchar(255) not null,
    primary key (id)
);

create table account_role (
    id bigint not null,
    name varchar(255) not null unique,
    primary key (id)
);

INSERT INTO account_role (id, name) VALUES
(1, 'ROLE_USER'),
(2, 'ROLE_TEACHER'),
(3, 'ROLE_ADMIN');

create table grade (
    value float4 not null,
    creation timestamp(6) with time zone,
    id bigint generated by default as identity,
    student_id bigint not null,
    subject_id bigint not null,
    teacher_id bigint not null,
    primary key (id)
);

create table subject (
    deleted boolean not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    leading_teacher_id bigint not null,
    description varchar(255),
    name varchar(255) not null,
    primary key (id)
);
comment on column subject.deleted is 'Soft-delete indicator';

create table subject_participants (
    participants_id bigint not null,
    subjects_id bigint not null,
    primary key (participants_id, subjects_id)
);

create table teacher_registration_token (
    reusable boolean not null,
    expires timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    token varchar(255) not null unique,
    primary key (id)
);

alter table if exists account
    add constraint FKcp50qbq0dv55q04m36vtc5qu9
    foreign key (role_id) references account_role;

alter table if exists grade
    add constraint FK4i4l8bv0kx1i1el7k7cac0vr0
    foreign key (student_id) references account;

alter table if exists grade
    add constraint FKhhw6hbmiyabjlm1jghr00m5d8
    foreign key (subject_id) references subject;

alter table if exists grade
    add constraint FKc33liuuykmbeyrh66e0g9qjif
    foreign key (teacher_id) references account;

alter table if exists subject
    add constraint FKjbrqoiv85ilqbdjbla59q5sv0
    foreign key (leading_teacher_id) references account;

alter table if exists subject_participants
    add constraint FK20oeyr1rvlm2njq4vj08mr5yw
    foreign key (participants_id) references account;

alter table if exists subject_participants
    add constraint FKido0292lx9h0tn031ok9wtxu6
    foreign key (subjects_id) references subject;
