spring.application.name=iwa25_project_backend

spring.datasource.url = jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:5432/${POSTGRES_DB:viruni}
spring.datasource.username = ${POSTGRES_USER:postgres}
spring.datasource.password = ${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name = org.postgresql.Driver

spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1

spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#To change logging levels in the app
#logging.level.org.springframework.web = trace
#logging.level.org.hibernate = debug
#logging.level.org.springframework.data=debug

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always

io.github.siniarski.iwa2025.final_project.jwtSecret = ZXdodHUyemQ4aW1hYndzOWduMDNvdnFsdXhrbHI4MDByMjEwdzc1d256OTNyOXl3
io.github.siniarski.iwa2025.final_project.jwtExpiration = 3600

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
